default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: localhost

development:
  <<: *default
  database: coding_challenge_development
  username: <%= ENV.fetch('DB_USERNAME') { 'postgresql' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgresql' } %>

test:
  <<: *default
  database: coding_challenge_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL') { 'undefined' } %>
